### ISSUE TITLE
CRITICAL - GetOrderBook Not Found

### ISSUE THREAD

**Issue by heavymanto** [JKorf/Kucoin.Net#146]
**Describe the bug**
From 6.30 AM of this day service responce is aways Not Found.  Is changed Api adress?

**To Reproduce**
by CryptoExchange.Net.Interfaces.CommonClients
![image](https://user-images.githubusercontent.com/6449169/166910773-186d9fdc-4a53-4540-9314-d9a979dc9e1b.png)

**Comment by JKorf** [comment]
Seems like they removed this endpoint.. I think it was already removed from their documentation some time ago, and they deactivated it now. Not much I can do about that. You can use `GetAggregatedFullOrderBookAsync` as a replacement

**Comment by masherak** [comment]
Same for me, thank you for your message

**Comment by JKorf** [comment]
In the latest version I've removed the deprecated endpoint and update the CommonSpotClient to use `GetAggregatedFullOrderBookAsync`

**Comment by masherak** [comment]
@JKorf I have problem with AggregatedFullOrderBook, I get TooManyRequests error very often on this endpoint, but I call it once per 5-10s. Do you plan to implement "Get Part Order Book(aggregated)" ?

There is description for AggregatedFullOrderBook endpoint on Kucoin -> "It is generally used by professional traders because it uses more server resources and traffic, and we have strict access frequency control."

**Comment by JKorf** [comment]
Partial book is available under `GetAggregatedPartialOrderBookAsync`

**Comment by masherak** [comment]
Solved! Thank you very much and sorry I missed this endpoint

**Comment by JKorf** [comment]
All good

**Comment by heavymanto** [comment]
Very interesting, you could use the GetAggregatedPartialOrderBookAsync method instead of GetAggregatedFullOrderBookAsync in the CryptoExchange.Net.Interfaces.CommonClients wrap to give the service more stability? Thank you
