### ISSUE TITLE
GetKlinesAsync UTC Problem

### ISSUE THREAD

**Issue by allcasper99** [JKorf/Kucoin.Net#87]
I am having UTC problem when I call the GetKlinesAsync method. To give an example, while it wants to get the data of 19:00 in 4 hours, it gets the data of 20:00 in the 4 hours. How can we find a solution to this?

**Comment by JKorf** [comment]
You need to send the timestamp you want in UTC kind. So say you want to get the klines from 10 hours ago you'd  pass in `DateTime.UtcNow.AddHours(-10)`. If you want a specific date you can do `new DateTime(2021, 11, 01, 19, 0, 0, DateTimeKind.Utc)`.
The 4 hour klines will start at set times though, which are 00:00, 04:00, 08:00 etc. So you won't be able to request 4 hour klines for say 03:00, which is I think the issue you're facing.

**Comment by allcasper99** [comment]
await kuClient.Spot.GetKlinesAsync("ETH-USDT", KucoinKlineInterval.FourHours);

how can i add UTC to this code?

**Comment by JKorf** [comment]
await kuClient.Spot.GetKlinesAsync("ETH-USDT", KucoinKlineInterval.FourHours, startTime: **START TIME**, endTime: **END TIME**); 
Pass in the times you're interested in into the start/end time parameters. If none provided then the most recent klines will be returned

**Comment by allcasper99** [comment]
thank you for the answer. This method allows us to draw candlesticks between 2 dates. This is not the solution to my problem

**Comment by JKorf** [comment]
There is no solution to what you're asking. The exchanges save the data in a specific format at specific times. As I said, for 4 hour klines intervals the data is recorded at 00:00, 04:00, 08:00, etc. You can't request 4 hour klines starting at 02:00 or something because that data is just not available. 
It is the same thing as trying to retrieve one hour klines, starting at 15 minutes into the hour.
